In [1]:
!pip install numpy

     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------------- ------------------------ 20.5/59.7 kB 640.0 kB/s eta 0:00:01
     -------------------------------------- 59.7/59.7 kB 626.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 2.6 MB/s eta 0:00:05
   - -------------------------------------- 0.4/12.6 MB 4.6 MB/s eta 0:00:03
   - -------------------------------------- 0.6/12.6 MB 4.8 MB/s eta 0:00:03
   -- ------------------------------------- 0.9/12.6 MB 6.0 MB/s eta 0:00:02
   --- ------------------------------------ 1.2/12.6 MB 5.8 MB/s eta 0:00:02
   --- ------------------------------------ 1.2/12.6 MB 4.8 MB/s eta 0:00:03
   ---- ----------------------------------- 1.4/12.6 MB 5.0 MB/s eta 0:00:03
   ---- ----------------------------------- 1.4/12.6 MB 5.0 MB/s eta 0:00:03
   ------ --------------------------------- 2.0/12.6 MB 5.3 MB/s eta 0:00:02
   --

import numpy

In [2]:
import numpy as np

1D ARRAY

In [31]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.size)
print(arr1.shape)

[1 2 3 4 5]
5
(5,)


In [25]:
arr2=np.array([1,2,3,4,5])
arr2.resize(2,5)
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [0 0 0 0 0]]
(2, 5)


2D ARRAY

In [34]:
arr3=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr3)

[[1 2 3 4 5]
 [1 2 3 4 5]]


BUILTIN FUNCTION IN NUMPY

In [36]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
arr4=np.arange(0,10,2)
print(arr4)
arr4.reshape(5,1)

[0 2 4 6 8]


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [43]:
## identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
arr5=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr5)
print("shape:",arr5.shape)
print("dimension:",arr5.ndim)
print("data type:",arr5.dtype)
print("item size(in bytes):",arr5.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
dimension: 2
data type: int64
item size(in bytes): 8


NUMPY VECTORIZED OPERATION

In [53]:
arr6=np.array([1,2,3,4,5])
arr7=np.array([1,1,1,1,1])

##Element wise addition
print(arr6+arr7)

##Element wise subtraction
print(arr6-arr7)

##Element wise multiplication
print(arr6*arr7)


[2 3 4 5 6]
[0 1 2 3 4]
[1 2 3 4 5]


ARRAY SLICING AND INDEXING

In [109]:
arr8=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr8)

print("\n")

##if i want to select only one elemrnt from matrix
print(arr8[0,0])

##if i want to select element 7,8,11,12 then i will use slice method
arr8[1:,2:]

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


1


array([[ 7,  8],
       [11, 12]])

MODIFY ARRAY ELEMENT

In [110]:
arr8[0,0]=100
print(arr8)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [111]:
arr8[2:,1:3]=0
print(arr8)

[[100   2   3   4]
 [  5   6   7   8]
 [  9   0   0  12]]


LOGICAL OPERATION

In [117]:
arr9=np.array([1,2,3,4,5,6,7,8,9,10])
arr9[arr9>5]

array([ 6,  7,  8,  9, 10])